=== ILobzhanidze/georgian-mss/collections/MS_Georg_d_2.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT tei:TEI (tei:teiHeader,tei:text)>
<!ATTLIST tei:TEI
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:teiHeader (tei:fileDesc,tei:profileDesc,tei:revisionDesc)>
<!ATTLIST tei:teiHeader
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:text (tei:body)>
<!ATTLIST tei:text
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:fileDesc (tei:titleStmt,tei:editionStmt,
                        tei:publicationStmt,tei:sourceDesc)>
<!ATTLIST tei:fileDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:profileDesc (tei:langUsage)>
<!ATTLIST tei:profileDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:revisionDesc (tei:change)+>
<!ATTLIST tei:revisionDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:body (tei:div)>
<!ATTLIST tei:body
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:titleStmt (tei:title,tei:respStmt)>
<!ATTLIST tei:titleStmt
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:editionStmt (tei:edition,tei:funder)>
<!ATTLIST tei:editionStmt
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:publicationStmt (tei:publisher,tei:address,
                               tei:distributor,tei:idno,
                               tei:availability)>
<!ATTLIST tei:publicationStmt
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:sourceDesc (tei:msDesc,tei:listWit,tei:listPerson,
                          tei:listPlace)>
<!ATTLIST tei:sourceDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:langUsage (tei:language)+>
<!ATTLIST tei:langUsage
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:change (#PCDATA)>
<!ATTLIST tei:change
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  when NMTOKEN #REQUIRED
  who CDATA #REQUIRED>

<!ELEMENT tei:respStmt (tei:persName,tei:resp+)>
<!ATTLIST tei:respStmt
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:edition (#PCDATA|tei:date)*>
<!ATTLIST tei:edition
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n CDATA #REQUIRED>

<!ELEMENT tei:funder (#PCDATA|tei:ref)*>
<!ATTLIST tei:funder
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:address (tei:orgName+,tei:street,tei:settlement,
                       tei:postCode,tei:country)>
<!ATTLIST tei:address
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:distributor (tei:email)>
<!ATTLIST tei:distributor
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:msDesc (tei:msIdentifier,tei:head,tei:msContents,
                      tei:physDesc,tei:history,tei:additional)>
<!ATTLIST tei:msDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED
  xml:lang NMTOKEN #REQUIRED>

<!ELEMENT tei:listWit (tei:witness)>
<!ATTLIST tei:listWit
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:listPerson (tei:person)>
<!ATTLIST tei:listPerson
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT tei:listPlace (tei:head+,tei:place)>
<!ATTLIST tei:listPlace
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT tei:language (#PCDATA)>
<!ATTLIST tei:language
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ident NMTOKEN #REQUIRED
  usage CDATA #REQUIRED>

<!ELEMENT tei:resp (#PCDATA)>
<!ATTLIST tei:resp
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:street (#PCDATA)>
<!ATTLIST tei:street
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:postCode (#PCDATA)>
<!ATTLIST tei:postCode
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:country (#PCDATA)>
<!ATTLIST tei:country
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:email (#PCDATA)>
<!ATTLIST tei:email
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:msIdentifier (tei:settlement,tei:repository,tei:idno)>
<!ATTLIST tei:msIdentifier
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:msContents (tei:summary,tei:textLang,tei:msItem+)>
<!ATTLIST tei:msContents
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:physDesc (tei:p,tei:objectDesc,tei:handDesc,tei:decoDesc,
                        tei:additions,tei:bindingDesc)>
<!ATTLIST tei:physDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:history (tei:origin,tei:provenance,tei:acquisition)>
<!ATTLIST tei:history
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:additional (tei:adminInfo)>
<!ATTLIST tei:additional
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:witness (#PCDATA|tei:ptr)*>
<!ATTLIST tei:witness
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:person (tei:persName)+>
<!ATTLIST tei:person
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:place (tei:placeName+,tei:idno)>
<!ATTLIST tei:place
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:repository (#PCDATA)>
<!ATTLIST tei:repository
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:summary (#PCDATA)>
<!ATTLIST tei:summary
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:msItem (tei:locus,tei:title,
                      (tei:rubric|(tei:incipit,tei:explicit)),tei:bibl,
                      tei:textLang)>
<!ATTLIST tei:msItem
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n CDATA #REQUIRED
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:objectDesc (tei:supportDesc,tei:layoutDesc)>
<!ATTLIST tei:objectDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  form NMTOKEN #REQUIRED>

<!ELEMENT tei:handDesc (tei:handNote)+>
<!ATTLIST tei:handDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  hands CDATA #REQUIRED>

<!ELEMENT tei:decoDesc (tei:decoNote)>
<!ATTLIST tei:decoDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:additions (tei:p)>
<!ATTLIST tei:additions
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:bindingDesc (tei:binding)>
<!ATTLIST tei:bindingDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:origin (tei:origPlace,tei:origDate)>
<!ATTLIST tei:origin
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:provenance (#PCDATA|tei:date)*>
<!ATTLIST tei:provenance
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:acquisition (#PCDATA)>
<!ATTLIST tei:acquisition
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:adminInfo (tei:recordHist,tei:availability)>
<!ATTLIST tei:adminInfo
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:ptr EMPTY>
<!ATTLIST tei:ptr
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  target CDATA #REQUIRED>

<!ELEMENT tei:rubric (#PCDATA|tei:ex|tei:hi)*>
<!ATTLIST tei:rubric
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:incipit (#PCDATA|tei:gap|tei:lb)*>
<!ATTLIST tei:incipit
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:explicit (#PCDATA|tei:lb)*>
<!ATTLIST tei:explicit
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:supportDesc (tei:support,tei:extent,tei:foliation+,
                           tei:collation,tei:condition)>
<!ATTLIST tei:supportDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  material NMTOKEN #REQUIRED>

<!ELEMENT tei:layoutDesc (tei:layout)>
<!ATTLIST tei:layoutDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:handNote (#PCDATA)>
<!ATTLIST tei:handNote
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  scope NMTOKEN #REQUIRED
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:binding (tei:p,tei:decoNote)>
<!ATTLIST tei:binding
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  notAfter CDATA #REQUIRED
  notBefore CDATA #REQUIRED>

<!ELEMENT tei:origPlace (tei:settlement)>
<!ATTLIST tei:origPlace
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:origDate (#PCDATA)>
<!ATTLIST tei:origDate
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  calendar NMTOKEN #REQUIRED
  notAfter CDATA #REQUIRED
  notBefore CDATA #REQUIRED>

<!ELEMENT tei:recordHist (tei:source)>
<!ATTLIST tei:recordHist
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:support (#PCDATA)>
<!ATTLIST tei:support
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:extent (tei:seg)+>
<!ATTLIST tei:extent
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:foliation (tei:p)>
<!ATTLIST tei:foliation
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT tei:collation (#PCDATA)>
<!ATTLIST tei:collation
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:condition (#PCDATA)>
<!ATTLIST tei:condition
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:layout EMPTY>
<!ATTLIST tei:layout
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  columns CDATA #REQUIRED
  writtenLines CDATA #REQUIRED>

<!ELEMENT tei:source (#PCDATA|tei:listBibl)*>
<!ATTLIST tei:source
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:seg (tei:dimensions|tei:num)>
<!ATTLIST tei:seg
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT tei:listBibl (tei:bibl)>
<!ATTLIST tei:listBibl
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:dimensions (tei:height,tei:width)>
<!ATTLIST tei:dimensions
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED
  unit NMTOKEN #REQUIRED>

<!ELEMENT tei:num (#PCDATA)>
<!ATTLIST tei:num
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED
  value CDATA #REQUIRED>

<!ELEMENT tei:height (#PCDATA)>
<!ATTLIST tei:height
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  quantity CDATA #REQUIRED>

<!ELEMENT tei:width (#PCDATA)>
<!ATTLIST tei:width
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  quantity CDATA #REQUIRED>

<!ELEMENT tei:title (#PCDATA|tei:title)*>
<!ATTLIST tei:title
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #IMPLIED
  xml:lang NMTOKEN #IMPLIED>

<!ELEMENT tei:persName (#PCDATA|tei:forename|tei:roleName)*>
<!ATTLIST tei:persName
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:lang NMTOKEN #IMPLIED>

<!ELEMENT tei:forename (#PCDATA)>
<!ATTLIST tei:forename
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:roleName (#PCDATA)>
<!ATTLIST tei:roleName
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:date (#PCDATA)>
<!ATTLIST tei:date
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  when NMTOKEN #REQUIRED>

<!ELEMENT tei:ref (#PCDATA)>
<!ATTLIST tei:ref
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  target CDATA #REQUIRED>

<!ELEMENT tei:publisher (#PCDATA|tei:orgName)*>
<!ATTLIST tei:publisher
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:orgName (#PCDATA)>
<!ATTLIST tei:orgName
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ref CDATA #IMPLIED
  type NMTOKEN #IMPLIED>

<!ELEMENT tei:settlement (#PCDATA)>
<!ATTLIST tei:settlement
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:idno (#PCDATA)>
<!ATTLIST tei:idno
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #IMPLIED>

<!ELEMENT tei:availability (tei:p)>
<!ATTLIST tei:availability
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  status NMTOKEN #IMPLIED>

<!ELEMENT tei:head (#PCDATA|tei:ex|tei:hi|tei:expan)*>
<!ATTLIST tei:head
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  hand CDATA #IMPLIED
  rend CDATA #IMPLIED
  xml:lang NMTOKEN #IMPLIED>

<!ELEMENT tei:expan (tei:ex)>
<!ATTLIST tei:expan
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:textLang (#PCDATA)>
<!ATTLIST tei:textLang
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  mainLang NMTOKEN #REQUIRED
  otherLangs NMTOKEN #IMPLIED>

<!ELEMENT tei:locus (#PCDATA)>
<!ATTLIST tei:locus
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  from NMTOKEN #REQUIRED
  to NMTOKEN #REQUIRED>

<!ELEMENT tei:gap EMPTY>
<!ATTLIST tei:gap
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  quantity CDATA #REQUIRED
  reason NMTOKEN #REQUIRED
  unit NMTOKEN #REQUIRED>

<!ELEMENT tei:lb EMPTY>
<!ATTLIST tei:lb
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:hi (#PCDATA|tei:add|tei:damage|tei:ex|tei:gap|tei:hi
                  |tei:lb|tei:unclear)*>
<!ATTLIST tei:hi
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  rend CDATA #IMPLIED>

<!ELEMENT tei:ex (#PCDATA)>
<!ATTLIST tei:ex
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:bibl (#PCDATA|tei:date|tei:idno|tei:publisher|tei:title)*>
<!ATTLIST tei:bibl
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #IMPLIED>

<!ELEMENT tei:p (#PCDATA|tei:add|tei:damage|tei:del|tei:ex|tei:gap
                 |tei:hi|tei:lb|tei:pb|tei:placeName|tei:ref|tei:unclear
                 |tei:foreign|tei:note|tei:q|tei:secFol|tei:subst)*>
<!ATTLIST tei:p
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  hand CDATA #IMPLIED
  rend CDATA #IMPLIED>

<!ELEMENT tei:foreign (#PCDATA|tei:ex|tei:unclear)*>
<!ATTLIST tei:foreign
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:lang NMTOKEN #REQUIRED>

<!ELEMENT tei:note (#PCDATA)>
<!ATTLIST tei:note
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:q (#PCDATA|tei:del|tei:ex|tei:lb|tei:unclear)*>
<!ATTLIST tei:q
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:secFol (#PCDATA|tei:ex|tei:locus)*>
<!ATTLIST tei:secFol
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:subst (tei:del,tei:add,tei:lb)>
<!ATTLIST tei:subst
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:decoNote (#PCDATA)>
<!ATTLIST tei:decoNote
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:placeName (#PCDATA|tei:ex)*>
<!ATTLIST tei:placeName
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  key NMTOKEN #IMPLIED
  xml:lang NMTOKEN #IMPLIED>

<!ELEMENT tei:div (tei:div|tei:head|tei:lb|tei:p|tei:pb|tei:figure)*>
<!ATTLIST tei:div
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n CDATA #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT tei:figure (tei:head,tei:p+,tei:figDesc)>
<!ATTLIST tei:figure
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  rend CDATA #REQUIRED>

<!ELEMENT tei:figDesc (#PCDATA)>
<!ATTLIST tei:figDesc
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:unclear EMPTY>
<!ATTLIST tei:unclear
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  quantity CDATA #REQUIRED
  reason NMTOKEN #REQUIRED
  unit NMTOKEN #REQUIRED>

<!ELEMENT tei:damage (#PCDATA|tei:ex|tei:gap|tei:hi)*>
<!ATTLIST tei:damage
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT tei:add (#PCDATA|tei:add|tei:del|tei:ex|tei:hi|tei:lb
                   |tei:unclear)*>
<!ATTLIST tei:add
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  hand CDATA #IMPLIED
  place NMTOKEN #IMPLIED
  style CDATA #IMPLIED>

<!ELEMENT tei:del (#PCDATA|tei:gap|tei:hi)*>
<!ATTLIST tei:del
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  quantity CDATA #IMPLIED
  rend NMTOKEN #IMPLIED
  unit NMTOKEN #IMPLIED>

<!ELEMENT tei:pb EMPTY>
<!ATTLIST tei:pb
  xmlns:tei CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n CDATA #REQUIRED
  xml:id NMTOKEN #REQUIRED>

=== ILobzhanidze/georgian-mss/collections/MS_Wardr_e_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "file:/D:/Git/georgian-mss/collections/MS_Georg_d_2.dtd">
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/css" href="MS_Georg.css"?>

<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="manuscript_55">
   <teiHeader>
      <fileDesc>
         <titleStmt>
            <title type="full">
               <title type="main">MS. Wardr. e. 1</title> 
               <title type="alt" xml:lang="en">Life of Saint Nisime</title>
               <title type="alt" xml:lang="ka">ცხოვრება წმიდისა ნისიმესი</title>
               <title type="alt" xml:lang="ka-la">cʻxovreba cmidisa nisimesi</title> 
            </title>
            <funder>JISC</funder>
            <principal>Gillian Evison</principal>
            <respStmt xml:id="IL">
               <persName>I. Lobzhanidze</persName>
               <resp>transcribed from original MS and converted to XML format</resp>
               <resp>markup and encoding</resp>
            </respStmt>
         </titleStmt>
         <editionStmt>
            <edition n="1">First publication edition, TEI P5.
               <date when="2019-02-21">21 February 2019</date>
            </edition>
            <funder>The project Wardrops' Collection Online is carried out within the framework of<ref target="http://rustaveli.org.ge/">Joint Research Programme of the University of Oxford and SRNSFG in Georgian Studies</ref></funder>
         </editionStmt>
         <publicationStmt>
            <publisher>Bodleian Library</publisher>
            <date calendar="#Gregorian">[Date when first made available]</date>
            <pubPlace>
               <address>
                  <addrLine>Department of Special Collections</addrLine>
                  <addrLine>Bodleian Library</addrLine>
                  <street>Broad Street</street>
                  <settlement>Oxford</settlement>
                  <postCode>OX1 3BG</postCode>
                  <addrLine>
                     <ref target="http://www.bodleian.ox.ac.uk/libraries/collections">Bodleian Library</ref>
                  </addrLine>
                  <addrLine>
                     <email>specialcollections.enquiries@bodleian.ox.ac.uk</email>
                  </addrLine>
               </address>
            </pubPlace>
            <distributor>
               <email>specialcollections.enquiries@bodleian.ox.ac.uk</email>
            </distributor>
            <idno type="msID">MS_Wardr_e_1</idno>
            <idno type="catalogue">Georgian</idno>
         </publicationStmt>
         <sourceDesc>
            <msDesc xml:id="MS_Wardr_e_1" xml:lang="en">
               <msIdentifier>
                  <country>United Kingdom</country>
                  <region type="county">Oxfordshire</region>
                  <settlement>Oxford</settlement>
                  <institution>Oxford University</institution>
                  <repository>Bodleian Library</repository>
                  <collection type="main">Oriental Manuscripts Wardrop Collection</collection>
                  <idno>MS. Wardr. e. 1</idno>
               </msIdentifier>
               <head>The life of Saint Nisime.</head>
               <msContents>
                  <summary>The life of Saint Nisime is well known for its different fragments in Syriac, Persian and Georgian languages. 
                     This manuscript belongs to XVIIIth century in accordance with watermark indicating "1784". This Manuscript consists of four parts with few additions and ornaments. 
                     The text is written in Mkhedruli script, while Asomtavruli script is used for titles, the first letters of paragraphs and sometimes for decoration. 
                  </summary>
                  <textLang mainLang="ka">Georgian</textLang>
                  <msItem xml:id="MS_Wardr_e_1-item1" n="1">
                     <locus from="2" to="222">pp. 2-22</locus>                     
                     <title xml:lang="en-Latn-x-lc" key="work_5">Life of St. Nisime</title>
                     <title xml:lang="ka" key="work_83">ცხოვრება წი<expan>&#x0360;<ex></ex></expan>სა ნისიმესი</title>
                     <incipit>              
                        <hi rend="color(FF0000)">Ⴋ</hi>აშინ თქუ̂ა მე წერილთა მრავალთა წარჳღე წიგნები<lb/>
                        სპარსეთით საბერძნეთად, დაკ<expan>&#x0360;<ex></ex></expan>დ წიგნები საბერძნეთით სპარ<lb/>
                        სეთად, და აღჳღი ქუ̂ჱლის საქმე ფ<expan>&#x0360;<ex></ex></expan>დ ალექსანდრიით, რ<expan>&#x0360;<ex></ex></expan> იყო ბერი ერთი<lb/>
                        შუ̂ჱნიერი, და კურთხეული და ყ<expan>&#x0360;<ex></ex></expan>ითურთ შემკობილი საქმითა ყოუ̂<lb/>
                        ლითა და იგი <damage><gap quantity="1" unit="chars" reason="illegible"/></damage> და ეკკლესიასა ალექსანდრიისასა:
                     </incipit>
                     <explicit>
                        რომლისა<lb/>
                        არს დიდება უ<lb/>
                        კუნითი უ<expan>&#x0360;<ex></ex></expan>კე<lb/>
                        რომლ’-<lb/>
                        ისა არს დიდე-<lb/>
                        ბა უკუნითი უკუ<lb/>
                        ნისამდე ამ<lb/>
                        ინ<lb/>
                       ..
                     </explicit>
                     <listBibl>
                        <bibl>CWC, 341</bibl>
                     </listBibl>                     
                     <textLang mainLang="ka">Georgian</textLang>
                  </msItem>
                  <msItem xml:id="MS_Wardr_e_1-item2" n="2">                     
                     <locus from="23" to="32">pp. 23-32</locus>   
                     <title xml:lang="ka-Latn-x-lc" key="work_6">cʻxovreba da mokʻalakʻeoba evpʻemianesi da żisa misisa alekʻsisa kacʻisa ġvtʻisa</title>
                     <title xml:lang="ka" key="work_6">ცხოვრება და მოქალაქეობა ევფემიანესი და ძისა მისისა ალექსისა კაცისა ღვთისა</title>
                     <incipit>              
                        ვინმე რომს ქალაქსა შ<expan>&#x0360;<ex></ex></expan>ა, კაცი მორწმუნე, და მართალი <lb/>
                        და მდიდარი ფ<expan>&#x0360;<ex></ex></expan>დ და სახელი მისი ავფემიანე, ამას ესხნეს მონანი...
                     </incipit>
                     <explicit>
                        უნთქუ̂ჱსვე აღმოჴდა სული სურნელებისა ადგილსა მისგან. ხ<expan>&#x0360;<ex></ex></expan> აღე-<lb/>
                        სრულა ნეტარი ესე, Ⴇთუ̂ჱსა მარტსა ათჩჳდმეტსა, და მიჳდა იგი<lb/>
                        წ<expan>&#x0360;<ex></ex></expan>ე ყ<expan>&#x0360;<ex></ex></expan>ისა, სადიდებელად მამისა და ძისა და წმიდისა სულისა ა<expan>&#x0360;<ex></ex></expan>წ და<lb/>
                        მარადის და უ<expan>&#x0360;<ex></ex></expan>კი უ<expan>&#x0360;<ex></ex></expan>ვე ამინ : Ⴋეოც მეყავ წ<expan>&#x0360;<ex></ex></expan>ო ღ<expan>&#x0360;<ex></ex></expan>ისბო, ცრლ<lb/>
                        ჳლს ზირაქს :
                     </explicit>
                     <listBibl>
                        <bibl>CWC, 341</bibl>
                     </listBibl>
                     <textLang mainLang="ka">Georgian</textLang>
                  </msItem>
                  <msItem xml:id="MS_Wardr_e_1-item3" n="3">
                     <locus from="32" to="32">pp. 32</locus>                      
                     <title xml:lang="en-Latn-x-lc" key="work_8">Acrostic on the name Aleksi, followed by a prayer for the scribe Zirak'i</title>
                     <title xml:lang="ka" key="work_6">ცხოვრება და მოქალაქეობა ევფემიანესი და ძისა მისისა ალექსისა კაცისა ღვთისა</title>
                     <listBibl>
                        <bibl>CWC, 341</bibl>
                     </listBibl>
                     <textLang mainLang="ka">Georgian</textLang>
                  </msItem>
                  <msItem xml:id="MS_Wardr_e_1-item4" n="4">
                     <locus from="1" to="8">pp. 1-8</locus> 
                     <title xml:lang="ka-Latn-x-lc" key="work_9">galoba moc'ik'ulisa</title>
                     <title xml:lang="ka" key="work_9">გალობა მოციქულისა</title>
                     <incipit>
                        <hi rend="color(FF0000)">Ⴑ</hi>ასუფეველი ცათა ღირსო რ<expan>&#x0360;<ex></ex></expan>ლიცაჲ და იმკჳდრე.<lb/>
                        და მზრახუ̂ჱლ ზეციერ. იქმენ შენ სიტყუ̂ასა;, მრწ-<lb/>
                        მუნებელნი ღ<expan>&#x0360;<ex></ex></expan>ის-მეტყუ̂ჱლებათა’ შენთა’, და ქადაგების-<lb/>
                        ანი’, და იფარენ ვედრებითა შენითა:
                     </incipit>
                     <explicit> 
                        Ⴑ<expan>&#x0360;<ex></ex></expan>ნსა შემცუ̂ჱლსა, სად ნა <damage><gap quantity="1" unit="chars" reason="illegible"/></damage><lb/>
                        Ⴞარდაქცეულებ, რტო დაცჳენ <damage><gap quantity="1" unit="chars" reason="illegible"/></damage><lb/>
                        Ⴈანი შენნი, ა’ღარ ჰფშვან სუნელთა,<lb/>
                        Ⴃავბილთა ფერი, ბაგითურთ <gap reason="illegible" quantity="1" unit="letter"/>გხდომ<gap reason="illegible" quantity="2" unit="letter"/> <damage><gap quantity="1" unit="chars" reason="illegible"/></damage>
                     </explicit>                     
                     <listBibl>
                        <bibl>CWC, 341</bibl>
                     </listBibl>
                     <textLang mainLang="ka">Georgian</textLang>
                  </msItem>
               </msContents>
               <physDesc>
                  <objectDesc form="leaf">
                     <supportDesc material="paper">
                        <support>The Manuscript is written on paper. The first and the last page is damaged</support>
                        <extent>
